all:
  hosts:
    master1:
      ansible_host: 51.20.86.9
    master2:
      ansible_host: 16.171.2.176
    master3:
      ansible_host: 16.171.56.163
    worker1:
      ansible_host: 16.170.234.71
    worker2:
      ansible_host: 13.53.177.205
    worker3:
      ansible_host: 16.16.100.72

  children:
    masters:
      hosts:
        master1:
        master2:
        master3:
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ../terraform/provision-vms/master-key.pem
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

    workers:
      hosts:
        worker1:
        worker2:
        worker3:
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ../terraform/provision-vms/worker-key.pem
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  vars:
    lb_dns_name: k8s-master-nlb-8aab4aa887b7b4f3.elb.eu-north-1.amazonaws.com:6443

