all:
  hosts:
    master1:
      ansible_host: YOUR_MASTER1_IP_HERE
    master2:
      ansible_host: YOUR_MASTER2_IP_HERE
    master3:
      ansible_host: YOUR_MASTER3_IP_HERE
    worker1:
      ansible_host: YOUR_WORKER1_IP_HERE
    worker2:
      ansible_host: YOUR_WORKER2_IP_HERE
    worker3:
      ansible_host: YOUR_WORKER3_IP_HERE
  children:
    masters:
      hosts:
        master1:
        master2:
        master3:
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ../terraform/provision-vms/master-key.pem
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    workers:
      hosts:
        worker1:
        worker2:
        worker3:
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ../terraform/provision-vms/worker-key.pem
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  vars:
    lb_dns_name: "YOUR_LOAD_BALANCER_DNS_HERE"